### ISSUE TITLE
Where and how do I report documentation bugs?

### ISSUE THREAD

**Issue by levitte** [concrete5/documentation.concretecms.org#24]
In https://documentation.concretecms.org/building-website-concretecms/4-create-your-package-and-theme/3-create-the-empty-theme, there are some `use` statements that don't have the initial `\`.

Unfortunately, it seems I can't do an edit directly (see attached image), and I haven't been able to find where to otherwise report this sort of thing.

![foo](https://user-images.githubusercontent.com/698918/142844863-3fe7fd7a-543e-471d-a20d-0803599ed724.png)

**Comment by levitte** [comment]
https://documentation.concretecms.org/building-website-concretecms/4-create-your-package-and-theme/4-install-the-package-and-theme has similar bugs, and I run into the same problem there.

**Comment by levitte** [comment]
Without the initial `\`, the theme will simply not show.

Note: concreteCMS 9.0.1

**Comment by levitte** [comment]
After some fiddling, the initial `\` turns out not to be an issue after all.

However, where to report documentation bugs is still an unknown

**Comment by aembler** [comment]
This is probably the best place to leave feedback on the documentation site.

https://forums.concretecms.org/c/site-feedback/2

Thanks!
